name: Deploy to EC2

on:
   push:
      branches:
         - main

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         # Step 1: Checkout the code from the repository
         - name: Checkout code
           uses: actions/checkout@v2

         # Step 2: Set up Docker Buildx (for building Docker images)
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2

         # Step 3: Log in to Docker Hub (optional if you're pushing the image to a registry)
         - name: Log in to Docker Hub
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

         # Step 4: Build the Docker image
         - name: Build the Docker image
           run: |
              docker build -t ${{ secrets.DOCKER_USERNAME }}/story-weaver .

         # Step 5: Push the Docker image to Docker Hub
         - name: Push Docker image
           run: |
              docker tag ${{ secrets.DOCKER_USERNAME }}/story-weaver:latest ${{ secrets.DOCKER_USERNAME }}/story-weaver:latest
              docker push ${{ secrets.DOCKER_USERNAME }}/story-weaver:latest

         # Step 6: Deploy to EC2 via SSH
         - name: Deploy to EC2
           uses: appleboy/ssh-action@v0.1.6
           with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.EC2_SSH_KEY }}
              port: 22
              script: |
                 docker pull ${{ secrets.DOCKER_USERNAME }}/story-weaver:latest
                 docker stop story-weaver || true
                 docker rm story-weaver || true
                 docker run -d -p 80:3000 --name story-weaver --env-file .env ${{ secrets.DOCKER_USERNAME }}/story-weaver:latest
